"""
System vitality — living-kernel observation.

Eyes on the live ``SystemInstance`` graph: seat discovery, seat reports,
capability registry, and projection snapshot. **Observation only** — not a
plane of start/continue.

| Slice | Landed |
|-------|--------|

**Sample law:** raw-dog public seat APIs into ``meta.raw`` (``lineage: sampled``).
Product present interprets. No adapter maps in system vitality.
"""

from __future__ import annotations

from palm.system.vitality.benchmark import (
    DEFAULT_ITERATIONS,
    DEFAULT_RECIPE,
    KNOWN_RECIPES,
    RECIPE_IDLE,
    RECIPE_LOG_FILL,
    RECIPE_PROJECT_STRESS,
    RECIPE_PULSE,
    RECIPE_WALK,
    RECIPE_WORK_CYCLE,
    diff_load_points,
    extract_load_points,
    run_benchmark,
)
from palm.system.vitality.capabilities import (
    build_benchmark_capability,
    build_default_capabilities,
    build_emission_window_capability,
    build_loaded_bulk_capability,
    build_process_resources_capability,
    build_seat_walk_capability,
    sample_benchmark,
    sample_emission_window,
    sample_loaded_bulk,
    sample_process_resources,
    sample_seat_walk,
)
from palm.system.vitality.capability import (
    CapabilityFragment,
    SampleContext,
    VitalityCapability,
    intention_stub,
)
from palm.system.vitality.emission_window import coerce_actor_kind
from palm.system.vitality.probe import (
    ProbeCatalog,
    SeatProbe,
    attr_resolver,
    first_resolver,
    private_attr_resolver,
)
from palm.system.vitality.projection import (
    ProjectionOptions,
    VitalityProjection,
    VitalitySnapshot,
    project,
    project_seat_walk_only,
    project_top,
)
from palm.system.vitality.protocol import SeatReportable, try_native_report
from palm.system.vitality.raw import (
    prefer_native,
    sample_attrs,
    sample_method,
    sample_raw,
    sample_sequence,
)
from palm.system.vitality.registry import VitalityRegistry
from palm.system.vitality.report import (
    SeatReport,
    coerce_report,
    index_by_seat_id,
    reports_to_dicts,
)
from palm.system.vitality.schema import (
    ACTOR_KIND_AGENT,
    ACTOR_KIND_HUMAN,
    ACTOR_KIND_PEER,
    ACTOR_KIND_PROBE,
    ACTOR_KIND_SYSTEM,
    ACTOR_KIND_UNKNOWN,
    CAPABILITY_BENCHMARK,
    CAPABILITY_EMISSION_WINDOW,
    CAPABILITY_FRAGMENT_SCHEMA,
    CAPABILITY_LOADED_BULK,
    CAPABILITY_MONITOR_AGENT,
    CAPABILITY_PROCESS_RESOURCES,
    CAPABILITY_SEAT_WALK,
    CHANNEL_SYSTEM_LOG,
    CHANNEL_WORK_PLANE,
    COST_CHEAP,
    COST_EXPENSIVE,
    COST_MODERATE,
    DEFAULT_EMISSION_WINDOW_LIMIT,
    KIND_BOOT,
    KIND_ENGINE,
    KIND_LOG,
    KIND_OTHER,
    KIND_PLANE,
    KIND_PORT,
    KIND_SUPERVISOR,
    KIND_SUPERVISOR_SERVICE,
    KNOWN_ACTOR_KINDS,
    LINEAGE_ADAPTER,
    LINEAGE_NATIVE,
    LINEAGE_SAMPLED,
    MATURITY_INSTALLED,
    MATURITY_INTENTION,
    ROLE_OBSERVE,
    ROLE_TOOL,
    SEAT_BOOT_MEMBERSHIP,
    SEAT_EXECUTION,
    SEAT_INSTALL,
    SEAT_PLANES,
    SEAT_REPORT_SCHEMA,
    SEAT_SESSION_PLANE,
    SEAT_STRUCTURE,
    SEAT_SUPERVISOR,
    SEAT_SYSTEM_LOG,
    SEAT_WAIT_PLANE,
    SEAT_WORK_PLANE,
    STATE_ABSENT,
    STATE_DEGRADED,
    STATE_ERROR,
    STATE_OK,
    STATE_SKIPPED,
    VITALITY_SNAPSHOT_SCHEMA,
    supervisor_service_seat_id,
)
from palm.system.vitality.seats import (
    build_default_probes,
    default_probe_catalog,
    reset_default_probe_catalog_for_tests,
)
from palm.system.vitality.seats_registry import (
    default_vitality_registry,
    reset_default_vitality_registry_for_tests,
)
from palm.system.vitality.walk import (
    SeatWalkResult,
    WalkOptions,
    discover_seats,
    seat_walk,
    walk_result,
)

__all__ = [
    "ACTOR_KIND_AGENT",
    "ACTOR_KIND_HUMAN",
    "ACTOR_KIND_PEER",
    "ACTOR_KIND_PROBE",
    "ACTOR_KIND_SYSTEM",
    "ACTOR_KIND_UNKNOWN",
    "CAPABILITY_BENCHMARK",
    "CAPABILITY_EMISSION_WINDOW",
    "CAPABILITY_FRAGMENT_SCHEMA",
    "CAPABILITY_LOADED_BULK",
    "CAPABILITY_MONITOR_AGENT",
    "CAPABILITY_PROCESS_RESOURCES",
    "CAPABILITY_SEAT_WALK",
    "CHANNEL_SYSTEM_LOG",
    "CHANNEL_WORK_PLANE",
    "COST_CHEAP",
    "COST_EXPENSIVE",
    "COST_MODERATE",
    "CapabilityFragment",
    "DEFAULT_EMISSION_WINDOW_LIMIT",
    "DEFAULT_ITERATIONS",
    "DEFAULT_RECIPE",
    "KIND_BOOT",
    "KNOWN_ACTOR_KINDS",
    "KNOWN_RECIPES",
    "KIND_ENGINE",
    "KIND_LOG",
    "KIND_OTHER",
    "KIND_PLANE",
    "KIND_PORT",
    "KIND_SUPERVISOR",
    "KIND_SUPERVISOR_SERVICE",
    "LINEAGE_ADAPTER",
    "LINEAGE_NATIVE",
    "LINEAGE_SAMPLED",
    "MATURITY_INSTALLED",
    "MATURITY_INTENTION",
    "ProbeCatalog",
    "ProjectionOptions",
    "RECIPE_IDLE",
    "RECIPE_LOG_FILL",
    "RECIPE_PROJECT_STRESS",
    "RECIPE_PULSE",
    "RECIPE_WALK",
    "RECIPE_WORK_CYCLE",
    "ROLE_OBSERVE",
    "ROLE_TOOL",
    "SEAT_STRUCTURE",
    "SEAT_BOOT_MEMBERSHIP",
    "SEAT_EXECUTION",
    "SEAT_INSTALL",
    "SEAT_PLANES",
    "SEAT_REPORT_SCHEMA",
    "SEAT_SESSION_PLANE",
    "SEAT_SUPERVISOR",
    "SEAT_SYSTEM_LOG",
    "SEAT_WAIT_PLANE",
    "SEAT_WORK_PLANE",
    "STATE_ABSENT",
    "STATE_DEGRADED",
    "STATE_ERROR",
    "STATE_OK",
    "STATE_SKIPPED",
    "SampleContext",
    "SeatProbe",
    "SeatReport",
    "SeatReportable",
    "SeatWalkResult",
    "VITALITY_SNAPSHOT_SCHEMA",
    "VitalityCapability",
    "VitalityProjection",
    "VitalityRegistry",
    "VitalitySnapshot",
    "WalkOptions",
    "attr_resolver",
    "build_benchmark_capability",
    "build_default_capabilities",
    "build_default_probes",
    "build_emission_window_capability",
    "build_loaded_bulk_capability",
    "build_process_resources_capability",
    "build_seat_walk_capability",
    "coerce_actor_kind",
    "coerce_report",
    "default_probe_catalog",
    "default_vitality_registry",
    "diff_load_points",
    "discover_seats",
    "extract_load_points",
    "first_resolver",
    "index_by_seat_id",
    "intention_stub",
    "prefer_native",
    "private_attr_resolver",
    "project",
    "run_benchmark",
    "sample_attrs",
    "sample_benchmark",
    "sample_emission_window",
    "sample_loaded_bulk",
    "sample_method",
    "sample_process_resources",
    "sample_raw",
    "sample_sequence",
    "project_seat_walk_only",
    "project_top",
    "reports_to_dicts",
    "reset_default_probe_catalog_for_tests",
    "reset_default_vitality_registry_for_tests",
    "sample_seat_walk",
    "seat_walk",
    "supervisor_service_seat_id",
    "try_native_report",
    "walk_result",
]
